### ISSUE TITLE
400 Bad Request (OAuth::Unauthorized)

### ISSUE THREAD

**Issue by MichaelSp** [RISCfuture/dropbox#53]
From your latest release:

```
/home/pi/.rvm/gems/ruby-2.0.0-p247/gems/oauth-0.4.7/lib/oauth/consumer.rb:216:in `token_request': 400 Bad Request (OAuth::Unauthorized)
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/oauth-0.4.7/lib/oauth/consumer.rb:136:in `get_request_token'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/dropbox-1.3.0/lib/dropbox/session.rb:70:in `initialize'
        from sync.rb:7:in `new'
        from sync.rb:7:in `<main>'
```

**Comment by Undistraction** [comment]
+1

**Comment by jasperkennis** [comment]
Same here. I seem to remember Dropbox changed their security somewhat, might that be related?

**Comment by MichaelSp** [comment]
I use this instead: https://github.com/tumf/dropbox-folder-sync/
Works much better
